name = "naitive-hello-world"
main = "src/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Custom Domain Configuration
routes = [
  { pattern = "test.naitive.io", custom_domain = true }
]

# Disable workers.dev in production
workers_dev = false

# Environment variables (can be set via dashboard or wrangler secrets)
[vars]
ENVIRONMENT = "production"
APP_NAME = "NAItive AI Workspace Hub"

# Optional: KV namespace for session storage (for future auth implementation)
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id" 